version: '2'

services:
  client:
    build:
      context: ./client-react
    depends_on:
      - nginx
      - rnkr
    image: rnkr/react-client:latest
    ports:
      - '3000:3000'

  db:
    container_name: elixir-rnkr-db
    image: postgres:11
    environment:
      POSTGRES_DB: rnkr_prod
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - /data/elixir-rnkr:/var/lib/postgresql/data

  nginx:
    build:
      context: ./nginx
    image: rnkr/nginx
    ports:
      - '80:80'
    restart: always

  rnkr:
    image: rnkr/rnkr:0.0.1
    container_name: rnkr
    command: /app/bin/rnkr_interface start
    depends_on:
      - db
      - nginx
    environment:
      - DB_NAME=rnkr_prod
      - DB_USER
      - DB_PASSWORD
      - DB_PORT
      - DB_HOST=db
      - MIX_ENV=prod
      - PHOENIX_HOST
      - SECRET_KEY_BASE
    ports:
      - '4000:4000'
