version: '2'

services:
  db:
    container_name: elixir-rnkr-db
    image: postgres:11
    environment:
      POSTGRES_DB: rnkr_dev
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ~/.data/elixir-rnkr:/var/lib/postgresql/data

  rnkr:
    build:
      context: .
    image: rnkr/rnkr:0.0.1
    container_name: rnkr
    command: /app/bin/rnkr_interface start
    depends_on:
      - db
    environment:
      DB_NAME: rnkr_dev
      DB_USER: rnkr
      DB_PASSWORD: letmein
      DB_PORT: 5432
      DB_HOST: db
      PHOENIX_HOST: localhost
      SECRET_KEY_BASE: WAYwxlhuIlr2ydMffb2IWf7ivRE/662dKKo+3jqcojVHe4uhRwTDptf4k9/Kx9RY
    ports:
      - '4000:4000'
      - '8080:80'
