version: '2'

services:
  db:
    container_name: elixir-rnkr-db
    image: postgres:11
    environment:
      POSTGRES_DB: rnkr_dev
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '${DB_PORT}:5432'
    volumes:
      - ~/.data/elixir-rnkr:/var/lib/postgresql/data
