version: '2'

services:
  db:
    container_name: elixir-rnkr-db
    image: postgres:11
    environment:
      POSTGRES_DB: rnkr_dev
      POSTGRES_USER: rnkr
      POSTGRES_PASSWORD: letmein
    ports:
      - '5432:5432'
    volumes:
      - ~/.data/elixir-rnkr:/var/lib/postgresql/data
